### ISSUE TITLE
Memory leak with optifine G7 in my pack

### ISSUE THREAD

**Issue by Mr-Syntax** [freeeranger/dark-caverns#5]
so i made this pack, and initially when i checked out the caves it was fine, but then open further inspection i had a huge lag spike and maxxed out my ram :( i will gladely include the mod again but ill sadly have to remove it for now

**Comment by Mr-Syntax** [comment]
https://www.curseforge.com/minecraft/modpacks/chosencraft

**Comment by freeeranger** [comment]
Thanks for reporting! If you have the time, a log file would be really appreciated. Also, is this something that happens frequently or have you only experienced it once?

**Comment by Mr-Syntax** [comment]
i didnt generate one but if you download the pack and just fly for 5-10 mins in one direction it happens, i think it might be a specific biome

**Comment by freeeranger** [comment]
Aight,, I'm gonna download your pack and see if I can reproduce the issue, but chances are it was 1: a one time thing, 2: not a thing with my mod but with having 200+ mods installed. I'll see what I can find though

**Comment by freeeranger** [comment]
closing for now since the mod doesn't seem to be the cause of this from my testing
